export const LISTBANKS_TRANFER = [
  {
    id: 1,
    name: 'Vietcombank',
    img: 'vietcombank.png',
    url_example: 'vcb.jpg',
    background: ['/vcb/nen1.png', '/vcb/nen2.png'],
    name_api: 'vietcombank',
  },
  {
    id: 2,
    name: 'ACB',
    img: 'acb.png',
    url_example: 'acb.png',
    background: [],
    name_api: 'acb',
  },
  {
    id: 3,
    name: 'Techcombank',
    img: 'techcombank.png',
    url_example: 'tcb.jpg',
    background: [],
    name_api: 'tech',
  },

  {
    id: 4,
    name: 'Agribank',
    img: 'agribank.png',
    url_example: 'agribank.png',
    background: [],
    name_api: 'agri',
  },
  {
    id: 5,
    name: 'MBBank',
    img: 'mbbank.png',
    url_example: 'mbb.png',
    background: [
      '/mbb/background1.png',
      '/mbb/background2.png',
      '/mbb/background3.png',
      '/mbb/background4.png',
      '/mbb/background5.png',
      '/mbb/background6.png',
      '/mbb/background7.png',
      '/mbb/background8.png',
      '/mbb/background9.png',
      '/mbb/background10.png',
      '/mbb/background11.png',
      '/mbb/background12.png',
      '/mbb/background13.png',
      '/mbb/background14.png',
      '/mbb/background15.png',
      '/mbb/background16.png',
    ],
    name_api: 'mb',
    // update: true,
  },
  {
    id: 6,
    name: 'MSB',
    img: 'msb.png',
    url_example: 'msb.JPG',
    background: [],
    name_api: 'msb',
    // update: true,

  },
  {
    id: 7,
    name: 'Sacombank',
    img: 'sacombank.png',
    url_example: 'scb.jpg',
    background: [],
    name_api: 'scb',
  },
  {
    id: 8,
    name: 'VPBank',
    img: 'vpbank.png',
    url_example: 'vpb.jpg',
    background: [],
    name_api: 'vpb',
    update: true,
  },
  {
    id: 9,
    name: 'BIDV',
    img: 'bidv.png',
    url_example: 'bidv.jpg',
    background: [],
    name_api: 'bidv',
    update: true,
  },
  {
    id: 10,
    name: 'VietinBank',
    img: 'vietinbank.png',
    url_example: 'vtb.png',
    background: [],
    name_api: 'vtb',
    update: true,
  },
  {
    id: 11,
    name: 'Momo',
    img: 'momo.png',
    url_example: 'momo.jpg',
    background: [],
    name_api: 'momo',
    update: true,
  },
  {
    id: 12,
    name: 'OCB',
    img: 'ocb.png',
    url_example: '',
    background: [],
    name_api: 'ocb',
    update: true,
  },
  {
    id: 13,
    name: 'TpBank',
    img: 'tpbank.png',
    url_example: '',
    background: [],
    name_api: 'tpbank',
    update: true,
  },
  {
    id: 14,
    name: 'VIB',
    img: 'vib.png',
    url_example: '',
    background: [],
    name_api: 'vib',
    update: true,

  },
  {
    id: 15,
    name: 'Nam Á Bank',
    img: 'NAB.png',
    url_example: '',
    background: [],
    name_api: 'nab',
    update: true,
  },
  {
    id: 16,
    name: 'SHB',
    img: 'shb.png',
    url_example: '',
    background: [],
    name_api: 'shb',
    update: true,
  }

]


export const LISTBANKS_VOLATILITY = [
  {
    id: 1,
    name: 'Vietcombank',
    img: 'vietcombank.png',
    url_example: 'vcb.png',
    background: ['/vcb/nen1.png', '/vcb/nen2.png'],
    name_api: 'vietcombank',
    // update: true,
  },
  {
    id: 2,
    name: 'ACB',
    img: 'acb.png',
    url_example: 'acb.png',
    background: [],
    name_api: 'acb',
    update: true,
  },
  {
    id: 3,
    name: 'Techcombank',
    img: 'techcombank.png',
    url_example: 'tcb.png',
    background: [],
    name_api: 'tech',
    // update: true,
  },

  {
    id: 4,
    name: 'Agribank',
    img: 'agribank.png',
    url_example: 'agribank.png',
    background: [],
    name_api: 'agri',
    // update: true,
  },
  {
    id: 5,
    name: 'MBBank',
    img: 'mbbank.png',
    url_example: 'mbb.png',
    background: [
      '/mbb/background1.png',
      '/mbb/background2.png',
      '/mbb/background3.png',
      '/mbb/background4.png',
      '/mbb/background5.png',
      '/mbb/background6.png',
      '/mbb/background7.png',
      '/mbb/background8.png',
      '/mbb/background9.png',
      '/mbb/background10.png',
      '/mbb/background11.png',
      '/mbb/background12.png',
      '/mbb/background13.png',
      '/mbb/background14.png',
      '/mbb/background15.png',
      '/mbb/background16.png',
    ],
    name_api: 'mbbank',
    update: true,
  },
  {
    id: 6,
    name: 'MSB',
    img: 'msb.png',
    url_example: 'msb.PNG',
    background: [],
    name_api: 'msb',
    update: true,
  },
  {
    id: 7,
    name: 'Sacombank',
    img: 'sacombank.png',
    url_example: 'scb.jpg',
    background: [],
    name_api: 'scb',
    update: true,
  },
  {
    id: 8,
    name: 'VPBank',
    img: 'vpbank.png',
    url_example: 'vpb.jpg',
    background: [],
    name_api: 'vpb',
    update: true,
  },
  {
    id: 9,
    name: 'BIDV',
    img: 'bidv.png',
    url_example: 'bidv.jpg',
    background: [],
    name_api: 'bidv',
    update: true,
  },
  {
    id: 10,
    name: 'VietinBank',
    img: 'vietinbank.png',
    url_example: 'vtb.png',
    background: [],
    name_api: 'vtb',
    update: true,
  },
  {
    id: 11,
    name: 'Momo',
    img: 'momo.png',
    url_example: 'momo.jpg',
    background: [],
    name_api: 'momo',
    update: true,
  },
  {
    id: 12,
    name: 'OCB',
    img: 'ocb.png',
    url_example: '',
    background: [],
    name_api: 'ocb',
    update: true,
  },
  {
    id: 13,
    name: 'TpBank',
    img: 'tpbank.png',
    url_example: '',
    background: [],
    name_api: 'tpbank',
    update: true,
  },
  {
    id: 14,
    name: 'VIB',
    img: 'vib.png',
    url_example: '',
    background: [],
    name_api: 'vib',
    update: true,

  },
  {
    id: 15,
    name: 'Nam Á Bank',
    img: 'NAB.png',
    url_example: '',
    background: [],
    name_api: 'nab',
    update: true,
  },
  {
    id: 16,
    name: 'SHB',
    img: 'shb.png',
    url_example: '',
    background: [],
    name_api: 'shb',
    update: true,
  }
]

export const LISTBANKS_BALANCE = [
  {
    id: 1,
    name: 'Vietcombank',
    img: 'vietcombank.png',
    url_example: 'vcb.png',
    background: ['/vcb/nen1.png', '/vcb/nen2.png'],
    name_api: 'vietcombank',
    update: true,
  },
  {
    id: 2,
    name: 'MBBank',
    img: 'mbbank.png',
    url_example: 'mbb.png',
    background: [
      '/mbb/background1.png',
      '/mbb/background2.png',
      '/mbb/background3.png',
      '/mbb/background4.png',
      '/mbb/background5.png',
      '/mbb/background6.png',
      '/mbb/background7.png',
      '/mbb/background8.png',
      '/mbb/background9.png',
      '/mbb/background10.png',
      '/mbb/background11.png',
      '/mbb/background12.png',
      '/mbb/background13.png',
      '/mbb/background14.png',
      '/mbb/background15.png',
      '/mbb/background16.png',
    ],
    name_api: 'mbbank',
    update: true,
  },
  {
    id: 3,
    name: 'ACB',
    img: 'acb.png',
    url_example: 'vtb.png',
    background: [],
    name_api: 'acb',
    update: true,
  },

  {
    id: 4,
    name: 'Techcombank',
    img: 'techcombank.png',
    url_example: '',
    background: [],
    name_api: 'tech',
    update: true,
  },
  {
    id: 5,
    name: 'Agribank',
    img: 'agribank.png',
    url_example: '',
    background: [],
    name_api: 'agri',
    update: true,
  },
  {
    id: 6,
    name: 'MSB',
    img: 'msb.png',
    url_example: 'msb.PNG',
    background: [],
    name_api: 'msb',
    update: true,
  },
  {
    id: 7,
    name: 'Sacombank',
    img: 'sacombank.png',
    url_example: 'scb.jpg',
    background: [],
    name_api: 'scb',
    update: true,
  },
  {
    id: 8,
    name: 'VPBank',
    img: 'vpbank.png',
    url_example: 'vpb.jpg',
    background: [],
    name_api: 'vpb',
    update: true,
  },
  {
    id: 9,
    name: 'BIDV',
    img: 'bidv.png',
    url_example: 'bidv.jpg',
    background: [],
    name_api: 'bidv',
    update: true,
  },
  {
    id: 10,
    name: 'VietinBank',
    img: 'vietinbank.png',
    url_example: 'vtb.png',
    background: [],
    name_api: 'vtb',
    update: true,
  },
  {
    id: 11,
    name: 'Momo',
    img: 'momo.png',
    url_example: 'momo.jpg',
    background: [],
    name_api: 'momo',
    update: true,
  },
  {
    id: 12,
    name: 'OCB',
    img: 'ocb.png',
    url_example: '',
    background: [],
    name_api: 'ocb',
    update: true,
  },
  {
    id: 13,
    name: 'TpBank',
    img: 'tpbank.png',
    url_example: '',
    background: [],
    name_api: 'tpbank',
    update: true,
  },
  {
    id: 14,
    name: 'VIB',
    img: 'vib.png',
    url_example: '',
    background: [],
    name_api: 'vib',
    update: true,

  },
  {
    id: 15,
    name: 'Nam Á Bank',
    img: 'NAB.png',
    url_example: '',
    background: [],
    name_api: 'nab',
    update: true,
  },
  {
    id: 16,
    name: 'SHB',
    img: 'shb.png',
    url_example: '',
    background: [],
    name_api: 'shb',
    update: true,
  }
]
