export const LISTBANKS_TRANFER = [
  {
    id: 1,
    name: 'Vietcombank',
    img: 'vietcombank.png',
    url_example: 'vcb.jpg',
    background: ['/vcb/nen1.png', '/vcb/nen2.png'],
  },
  {
    id: 2,
    name: 'ACB',
    img: 'acb.png',
    url_example: 'acb.png',
    background: [],
  },
  {
    id: 3,
    name: 'Techcombank',
    img: 'techcombank.png',
    url_example: 'tcb.jpg',
    background: [],
  },

  {
    id: 4,
    name: 'Agribank',
    img: 'agribank.png',
    url_example: 'agribank.png',
    background: [],
  },
  {
    id: 5,
    name: 'MBBank',
    img: 'mbbank.png',
    url_example: 'mbb.png',
    background: [
      '/mbb/background1.png',
      '/mbb/background2.png',
      '/mbb/background3.png',
      '/mbb/background4.png',
      '/mbb/background5.png',
      '/mbb/background6.png',
      '/mbb/background7.png',
      '/mbb/background8.png',
      '/mbb/background9.png',
      '/mbb/background10.png',
      '/mbb/background11.png',
      '/mbb/background12.png',
      '/mbb/background13.png',
      '/mbb/background14.png',
      '/mbb/background15.png',
      '/mbb/background16.png',
    ],
  },
  {
    id: 6,
    name: 'MSB',
    img: 'msb.png',
    url_example: 'msb.JPG',
    background: [],
  },
]

export const LISTBANKS_VOLATILITY = [
  {
    id: 1,
    name: 'Vietcombank',
    img: 'vietcombank.png',
    url_example: 'vcb.png',
    background: ['/vcb/nen1.png', '/vcb/nen2.png'],
  },
  {
    id: 2,
    name: 'ACB',
    img: 'acb.png',
    url_example: 'acb.png',
    background: [],
  },
  {
    id: 3,
    name: 'Techcombank',
    img: 'techcombank.png',
    url_example: 'tcb.png',
    background: [],
  },

  {
    id: 4,
    name: 'Agribank',
    img: 'agribank.png',
    url_example: 'agribank.png',
    background: [],
  },
  {
    id: 5,
    name: 'MBBank',
    img: 'mbbank.png',
    url_example: 'mbb.png',
    background: [
      '/mbb/background1.png',
      '/mbb/background2.png',
      '/mbb/background3.png',
      '/mbb/background4.png',
      '/mbb/background5.png',
      '/mbb/background6.png',
      '/mbb/background7.png',
      '/mbb/background8.png',
      '/mbb/background9.png',
      '/mbb/background10.png',
      '/mbb/background11.png',
      '/mbb/background12.png',
      '/mbb/background13.png',
      '/mbb/background14.png',
      '/mbb/background15.png',
      '/mbb/background16.png',
    ],
  },
  {
    id: 6,
    name: 'MSB',
    img: 'msb.png',
    url_example: 'msb.PNG',
    background: [],
  },
]

export const LISTBANKS_BALANCE = [
  {
    id: 1,
    name: 'Vietcombank',
    img: 'vietcombank.png',
    url_example: 'vcb.png',
    background: ['/vcb/nen1.png', '/vcb/nen2.png'],
  },
  {
    id: 2,
    name: 'MBBank',
    img: 'mbbank.png',
    url_example: 'mbb.png',
    background: [
      '/mbb/background1.png',
      '/mbb/background2.png',
      '/mbb/background3.png',
      '/mbb/background4.png',
      '/mbb/background5.png',
      '/mbb/background6.png',
      '/mbb/background7.png',
      '/mbb/background8.png',
      '/mbb/background9.png',
      '/mbb/background10.png',
      '/mbb/background11.png',
      '/mbb/background12.png',
      '/mbb/background13.png',
      '/mbb/background14.png',
      '/mbb/background15.png',
      '/mbb/background16.png',
    ],
  },
  {
    id: 3,
    name: 'ACB',
    img: 'acb.png',
    url_example: 'vtb.png',
    background: [],
  },

  {
    id: 4,
    name: 'Techcombank',
    img: 'techcombank.png',
    url_example: '',
    background: [],
  },
  {
    id: 5,
    name: 'Agribank',
    img: 'agribank.png',
    url_example: '',
    background: [],
  },
  {
    id: 6,
    name: 'MSB',
    img: 'msb.png',
    url_example: 'msb.PNG',
    background: [],
  },
]
